<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Jida Intezaar si, Aaj Rabba Wohi Din Aaya hai</name>
   <tag></tag>
   <elementGuidId>e7e7effa-ba4f-48b0-afb9-aa9524674325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='comment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Jida Intezaar si, Aaj Rabba Wohi Din Aaya hai&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7c1ca3a5-1a82-4c41-963a-7b8cdb19950c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comment</value>
      <webElementGuid>367dce4b-e379-4b43-863d-41a7b0b5bd88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jida Intezaar si, Aaj Rabba Wohi Din Aaya hai</value>
      <webElementGuid>44a842ae-1aed-4d35-832e-de899bb3ebb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comment&quot;)</value>
      <webElementGuid>0066a760-25ea-4594-8317-f0b47a477828</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='comment']</value>
      <webElementGuid>2ed9717f-8afb-4bfa-93e2-f5ae310fa61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='summary']/div/div/div[6]/div[2]/p</value>
      <webElementGuid>218201a1-ff20-4022-b69a-25225415dda2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comment'])[1]/following::p[1]</value>
      <webElementGuid>4e73000b-c00c-4971-9cc9-e8ed5cfb8781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit Date'])[1]/following::p[2]</value>
      <webElementGuid>cf62c35e-27b1-4479-afd4-749ccd847d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to Homepage'])[1]/preceding::p[1]</value>
      <webElementGuid>d7ed4db7-6b6a-4959-b25c-5f0b3bd75032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CURA Healthcare Service'])[3]/preceding::p[2]</value>
      <webElementGuid>3a7de165-2f1d-49b7-82f0-3a3b3fafc510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jida Intezaar si, Aaj Rabba Wohi Din Aaya hai']/parent::*</value>
      <webElementGuid>9563b210-7706-4d97-9b9f-40c5ceed8e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/p</value>
      <webElementGuid>130da8e8-7d3d-49f8-9be4-09fe3e916ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'comment' and (text() = 'Jida Intezaar si, Aaj Rabba Wohi Din Aaya hai' or . = 'Jida Intezaar si, Aaj Rabba Wohi Din Aaya hai')]</value>
      <webElementGuid>25fb6e03-a7e7-487f-a778-cde7910961b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
